version: '3'

services:
  front:
    build: .
    volumes:
      - ./:/app/grade
    networks:
      - code-network
  nginx:
    image: nginx:latest
    volumes:
      - ./:/app/grade
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
